name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-php:
    name: Check that composer dependencies can be installed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          tools: composer:v2
      - name: Composer install
        run: composer install
  test-node:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16, 18]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
